---
# These should be standard for every installation

#### WARNING: When using a disconnected satellite, content_source must be "file" or playbook will fail
#### Copy remote gpg keys, certificates, etc.. to your files directory.

# Content credentials
content_credentials:
  - name: "RedHatGPG"
    content_type: "gpg_key"
    content_source: "file"
    content_path: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
    state: "present"
  - name: "RedHatSSL"
    content_type: "cert"
    content_source: "file"
    content_path: "/etc/rhsm/ca/redhat-uep.pem"
    state: "present"
  - name: "CentOS9OfficialGPG"
    content_type: "gpg_key"
    content_source: "url"
    content_path: "https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official-SHA256"
    state: "present"
  - name: "OracleLinux7GPG"
    content_type: "gpg_key"
    content_source: "url"
    content_path: "https://yum.oracle.com/RPM-GPG-KEY-oracle-ol7"
    state: "present"
  - name: "CentOS79GPG"
    content_type: "gpg_key"
    content_source: "url"
    content_path: "https://vault.centos.org/7.9.2009/os/x86_64/RPM-GPG-KEY-CentOS-7"
    state: "present"
  - name: "MicrosoftGPG"
    content_type: "gpg_key"
    content_source: "url"
    content_path: "https://packages.microsoft.com/keys/microsoft.asc"
    state: "present"
  - name: "EPEL7GPG"
    content_type: "gpg_key"
    content_source: "url"
    content_path: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    state: "present"
  - name: "EPEL8GPG"
    content_type: "gpg_key"
    content_source: "url"
    content_path: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8"
    state: "present"
  - name: "EPEL9GPG"
    content_type: "gpg_key"
    content_source: "url"
    content_path: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9"
    state: "present"
  - name: "POSTGRES-RHEL"
    content_type: "gpg_key"
    content_source: "url"
    content_path: "https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL"
    state: "present"
