---

# vars file for rhis_post
ipa_server_fqdn: "{{ groups['idm_primary'][0] }}"

rhis_default_git_dest: "~/rhis_ee_repos"
redhat_container_registry_url: "registry.redhat.io"
redhat_registry_username: "{{ redhat_registry_username_vault }}"
redhat_registry_password: "{{ redhat_registry_password_vault }}"
automation_hub_token: "{{ automation_hub_token_vault }}"
private_hub_token: "{{ private_automation_hub24_token_vault }}"
private_hub_url: "https://{{ groups['aap_hubs'][0] }}/api/galaxy/"
aap_platform_host: "{{ groups['aap_controllers'][0] }}"
aap_platform_username: "{{ aap_admin_username_vault }}"
aap_platform_password: "{{ aap_admin_password_vault }}"

# AAP Authentication
aap_ldap_domain_map: "dc=,dc=ca"
aap_admin_username: "{{ aap_admin_username_vault }}"
aap_admin_password: "{{ aap_admin_password_vault }}"

active_controller: "{{ groups['aap_controllers'][0] }}"
active_aap_hub: "{{ groups['aap_hubs'][0] }}"
aap_validate_certs: false
ah_container_token: ""

satellite_ansible_callback_config_key: "{{ satellite_ansible_callback_config_key_vault }}"
