---

# content_exports definition

content_export_copies:
  - name: "Library"
    type: "library"
    destination_server: "satellite_disconnected.{{ _global_domain_name }}"
    export_version: "1.0"
    destination_folder: "/run/media/ansiblerunner/export"
