---

hg_test_hosts_rhel8:
  - fqdn: "hg-x86-64-rhel8-metal1.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel8_metal"
#    operatingsystem: "RHEL 8.10"
#    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    compute_resource: "baremetal"
    comment: "rhis_test_host deleteme"
    pxe_loader: "Grub2 UEFI"
    interfaces_attributes:
      - type: "interface"
        identifier: "{{ _default_provision_iface }}"
        domain: "{{ _default_domain }}"
        execution: true
        managed: true
        primary: true
        provision: true
        subnet: "{{ _global_domain_name }}"
        mac: "94:c6:91:a3:1d:6a"                   # c1s1n3
        ip: "{{ _default_network }}.201"

  - fqdn: "hg-x86-64-rhel8-vm1.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel8_vm"
    activation_keys: "SOE8_dev"
    lifecycle_environment: "Development"
    content_view: "SOE8"
    compute_resource: "VMware_Lab"
    compute_profile: "SOE_Medium"
#    operatingsystem: "RHEL 8.10"
#    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    ptable: "Kickstart default"
    pxe_loader: "Grub2 UEFI"
    mac: "00:50:56:ff:ff:ff"
    comment: "rhis_test_host deleteme"

  - fqdn: "soe8-dev-cis2-1.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel8_vm/dev/soe8_dev_cis2"
    compute_resource: "VMware_Lab"
    compute_profile: "SOE_Medium"
#    operatingsystem: "RHEL 8.10"
#    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    pxe_loader: "Grub2 UEFI"
    mac: "00:50:56:ff:ff:ff"
    comment: "rhis_test_host deleteme"

  - fqdn: "soe8-dev-jboss-1.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel8_vm/dev/soe8_dev_jboss"
    compute_resource: "VMware_Lab"
    compute_profile: "SOE_Medium"
#    operatingsystem: "RHEL 8.10"
#    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    pxe_loader: "Grub2 UEFI"
    mac: "00:50:56:ff:ff:ff"
    comment: "rhis_test_host deleteme"

  - fqdn: "soe8-dev-lamp-1.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel8_vm/dev/soe8_dev_lamp"
    compute_resource: "VMware_Lab"
    compute_profile: "SOE_Medium"
#    operatingsystem: "RHEL 8.10"
#    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    pxe_loader: "Grub2 UEFI"
    mac: "00:50:56:ff:ff:ff"
    comment: "rhis_test_host deleteme"

  - fqdn: "soe8-dev-wordpress-1.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel8_vm/dev/soe8_dev_wordpress"
    compute_resource: "VMware_Lab"
    compute_profile: "SOE_Medium"
#    operatingsystem: "RHEL 8.10"
#    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    pxe_loader: "Grub2 UEFI"
    mac: "00:50:56:ff:ff:ff"
    comment: "rhis_test_host deleteme"

  - fqdn: "soe8-qa-jboss-1.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel8_vm/qa/soe8_qa_jboss"
    compute_resource: "VMware_Lab"
    compute_profile: "SOE_Medium"
#    operatingsystem: "RHEL 8.10"
#    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    pxe_loader: "Grub2 UEFI"
    mac: "00:50:56:ff:ff:ff"
    comment: "rhis_test_host deleteme"

  - fqdn: "soe8-qa-lamp-1.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel8_vm/qa/soe8_qa_lamp"
    compute_resource: "VMware_Lab"
    compute_profile: "SOE_Medium"
#    operatingsystem: "RHEL 8.10"
#    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    pxe_loader: "Grub2 UEFI"
    mac: "00:50:56:ff:ff:ff"
    comment: "rhis_test_host deleteme"

  - fqdn: "soe8-qa-wordpress-1.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel8_vm/qa/soe8_qa_wordpress"
    compute_resource: "VMware_Lab"
    compute_profile: "SOE_Medium"
#    operatingsystem: "RHEL 8.10"
#    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    pxe_loader: "Grub2 UEFI"
    mac: "00:50:56:ff:ff:ff"
    comment: "rhis_test_host deleteme"
