---
satellite_subnets:
  - name: "{{ _global_domain_name }}"
    description: "{{ _global_domain_name }} network"
    network_type: "IPv4"
    network: "{{ _default_network }}.0"
    prefix: "{{ _default_network_prefix }}"
    mask: "{{ _default_network_mask }}"
    gateway: "{{ _default_network }}.1"
    dns_primary: "{{ _default_network }}.5"
    dns_secondary: "{{ _default_network }}.6"
    ipam: "Internal DB"
    from_ip: "{{ _default_network }}.100"
    to_ip: "{{ _default_network }}.199"
    boot_mode: "Static"
    discovery_capsule: "{{ satellite_fqdn }}"
    tftp_capsule: "{{ satellite_fqdn }}"
    dns_capsule: "{{ satellite_fqdn }}"
    template_capsule: "{{ satellite_fqdn }}"
    parameters:
      - name: "Parameter1"
        parameter_type: string
        value: "theParameter"
    remote_execution_capsules:
      - "{{ satellite_fqdn }}"
    domains:
      - "{{ satellite_domain }}"
    locations:
      - "{{ satellite_location }}"
    organizations:
      - "{{ satellite_organization }}"

  - name: "bond_subnet"
    description: "{{ _global_domain_name }} bond network"
    network_type: "IPv4"
    network: 192.168.142.0
    prefix: "{{ _default_network_prefix }}"
    mask: "{{ _default_network_mask }}"
    gateway: "{{ _default_network }}.1"
    dns_primary: "{{ _default_network }}.5"
    dns_secondary: "{{ _default_network }}.6"
    ipam: "None"
    boot_mode: "Static"
    dns_capsule: "{{ satellite_fqdn }}"
    domains:
      - "{{ satellite_domain }}"
    locations:
      - "{{ satellite_location }}"
    organizations:
      - "{{ satellite_organization }}"

  # - name: "azure.{{ _global_domain_name }}"
  #   description: "azure.{{ _global_domain_name }} network"
  #   network_type: "IPv4"
  #   network: "10.10.0.0"
  #   prefix: "22"
  #   mask: "255.255.252.0"
  #   gateway: "10.10.0.1"
  #   dns_primary: "10.10.0.5"
  #   dns_secondary: "10.10.0.6"
  #   ipam: "Internal DB"
  #   from_ip: "10.10.0.100"
  #   to_ip: "10.10.0.199"
  #   boot_mode: "Static"
  #   discovery_capsule: "{{ groups['sat_capsule'][0] }}"
  #   tftp_capsule: "{{ groups['sat_capsule'][0] }}"
  #   dns_capsule: "{{ groups['sat_capsule'][0] }}"
  #   template_capsule: "{{ groups['sat_capsule'][0] }}"
  #   parameters:
  #     - name: "Parameter1"
  #       parameter_type: string
  #       value: "theParameter"
  #   remote_execution_capsules:
  #     - "{{ groups['sat_capsule'][0] }}"
  #   domains:
  #     - "{{ groups['sat_capsule'][0] }}"
  #   locations:
  #     - "{{ groups['sat_capsule'][0] }}"
  #   organizations:
  #     - "{{ groups['sat_capsule'][0] }}"
