---

credentials:
  - name: "Automation_Hub"
    organization: "Default"
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    description: "Red Hat Automation Hub cred"
    state: present
    inputs:
      url: "https://cloud.redhat.com/api/automation-hub/"
      auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      token: "{{ redhat_automation_hub_token_vault }}"

  - name: "Private_Hub_community"
    organization: "Default"
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    description: "{{ _global_domain_name }} private automation hub allowable community content"
    state: present
    inputs:
      url: "https://aaphub24.{{ _global_domain_name }}/api/galaxy/content/community/"
      token: "{{ private_automation_hub24_token_vault }}"

  - name: "Private_Hub_rh-certified"
    organization: "Default"
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    description: "{{ _global_domain_name }} private automation hub allowable rh-certified repository"
    state: present
    inputs:
      url: "https://aaphub24.{{ _global_domain_name }}/api/galaxy/content/rh-certified/"
      token: "{{ private_automation_hub24_token_vault }}"

  - name: "Private_Hub_validated"
    organization: "Default"
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    description: "{{ _global_domain_name }} private automation hub allowable Red Hat validated content"
    state: present
    inputs:
      url: "https://aaphub24.{{ _global_domain_name }}/api/galaxy/content/validated/"
      token: "{{ private_automation_hub24_token_vault }}"

  - name: "ansible_github"
    organization: "Default"
    credential_type: "Source Control"
    description: "rhis_builder demo credential"
    state: present
    inputs:
      username: "{{ ansible_github_username_vault }}"
      password: "{{ ansible_github_gpat_vault }}"

  - name: "default_machine"
    organization: "Default"
    credential_type: "Machine"
    description: "The default local machine auth for demo systems"
    state: present
    inputs:
      username: "{{ default_environment_username_vault }}"
      password: "{{ default_environment_password_vault }}"

  - name: "idm_machine"
    organization: "Default"
    credential_type: "Machine"
    description: "The Identity Management machine auth for AAP"
    state: present
    inputs:
      username: "{{ aap_idm_machine_username_vault }}"
      password: "{{ aap_idm_machine_password_vault }}"

  - name: "default_vault"
    organization: "Default"
    credential_type: "Vault"
    description: "The default vault credential for demo projects"
    state: present
    inputs:
      vault_password: "{{ default_environment_password_vault }}"

  - name: "prod_satellite"
    organization: "Default"
    credential_type: "Red Hat Satellite 6"
    description: "login for satellite"
    state: present
    inputs:
      host: "{{ satellite_server_url }}"
      username: "{{ sat_inital_admin_username_vault }}"
      password: "{{ sat_inital_admin_password_vault }}"

  - name: "aaphub24_containers"
    organization: "Default"
    credential_type: "Container Registry"
    description: "Execution Environment Pull from aaphub24"
    state: present
    inputs:
      host: "https://aaphub24.{{ _global_domain_name }}/registry"
      username: "{{ sat_inital_admin_username_vault }}"
      password: "{{ sat_inital_admin_password_vault }}"
      verify_ssl: true
