---

vm_day_2_templates:
  - name: "VMwareCreateSnapshot"
    description: "Snaphot JBoss, LAMP and Wordpress test machines to Development"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_create_snapshot.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
          snap_name: testjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: testlamp2.{{ _global_domain_name }}
          snap_name: testlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: testwordpress2.{{ _global_domain_name }}
          snap_name: testwordpress2.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "VMwarePowerOffVM"
    description: "Power-off test machines"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_power_off_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwarePowerOnVM"
    description: "Power-on test machines"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_power_on_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwareRebootGuestOS"
    description: "Reboot test machines"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_reboot_guest_os.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwareRemoveAllSnaps"
    description: "Remove all snapshots from test machines"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_remove_all_snapshots.yml"
    become_enabled: true
    credentials:
      - "default_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
          snap_name: testjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: testlamp2.{{ _global_domain_name }}
          snap_name: testlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: testwordpress2.{{ _global_domain_name }}
          snap_name: testwordpress2.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "VMwareRestartVM"
    description: "Restart the test machine vm"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_restart_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}.ca"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwareRevertSnaps"
    description: "Revert the VM to a previous snapshot"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_revert_snapshot.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}.ca"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
          snap_name: testjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: testlamp2.{{ _global_domain_name }}
          snap_name: testlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: testwordpress2.{{ _global_domain_name }}
          snap_name: testwordpress.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "VMwareShutdownGuestOS"
    description: "Graceful shutdown of test machine vm"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_shutdown_guest_os.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}.ca"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwareSuspendVM"
    description: "Suspend test machine vm - use with caution"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_suspend_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}.ca"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "MonthlyPublishContent"
    description: "Publish all SOE Content"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "publish_only.yml"
    become_enabled: true
    credentials:
      - "default_machine"
      - "default_vault"
    variables:
      force_publish_all: true
      skip_publish_all: false
      description: "Published by rhis-builder-pipelines"
      satellite_validate_certs: true
      content_views:
        - name: "AAP24_Files"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "AAP24_RPMs"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "AAP25_Files"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "AAP25_RPMs"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "bootc_containers"
          environments:
            - "Library"
        - name: "CentOS79"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
            - "Development"
        - name: "CentOS_S9"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
            - "Development"
        - name: "convert2rhel7"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "convert2rhel8"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "EPEL8"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "EPEL9"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "JBoss8EAP74"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "JBoss9EAP74"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "LEAPP_2_RHEL8"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "LEAPP_2_RHEL9"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "mssqlserver2022_rhel9"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
        - name: "OEL79"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
            - "Development"
        - name: "SOE7"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
            - "Development"
            - "Qualification"
            - "Production"
        - name: "SOE8"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
            - "Development"
            - "Qualification"
            - "Production"
        - name: "SOE9"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
            - "Development"
            - "Qualification"
            - "Production"
        - name: "SOE9_aarch64"
          date_filter_name: "ErrataByDate"
          environments:
            - "Library"
            - "Development"
            - "Qualification"
            - "Production"

      composite_content_views:
        - name: "SOE_AAP24"
          environments:
            - "Library"
            - "SOE_Development"
        - name: "SOE_AAP25"
          environments:
            - "Library"
            - "SOE_Development"
        - name: "SOE8_JBoss"
          environments:
            - "Library"
            - "Development"
            - "Qualification"
            - "Production"
        - name: "SOE9_JBoss"
          environments:
            - "Library"
            - "Development"
            - "Qualification"
            - "Production"
        - name: "SOE8_EPEL"
          environments:
            - "Library"
            - "SOE_Development"
        - name: "SOE9_EPEL"
          environments:
            - "Library"
            - "SOE_Development"
            - "SOE_Qualification"
            - "SOE_Production"
        - name: "convert_CentOS2RHEL7"
          environments:
            - "Library"
            - "SOE_Development"
        - name: "convert_OEL2RHEL7"
          environments:
            - "Library"
            - "SOE_Development"
        - name: "LEAPP_7_2_8"
          environments:
            - "Library"
            - "SOE_Development"
        - name: "LEAPP_8_2_9"
          environments:
            - "Library"
            - "SOE_Development"
        - name: "SOE9_MSSQL"
          environments:
            - "Library"
            - "SOE_Development"
        - name: "SOE9_POS"
          environments:
            - "Library"
            - "SOE_Development"

  - name: "SOE_Base_Ansible_Callback"
    description: "Satellite build invoked Ansible Callback"
    job_type: "run"
    organization: "Default"
    inventory: "sat6.{{ _global_domain_name }}"
    project: "rhis-builder-day-2-ops"
    execution_environment: "satellite_ee"
    playbook: "post_provisioning_base.yml"
    become_enabled: true
    host_config_key: "{{ satellite_ansible_callback_config_key }}"
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      sysmessage_type: "base"
      time_timedaemon: "chrony"
      time_timeservers:
        - "time1.example.ca"
        - "time2.example.ca"
        - "time3.example.ca"
      time_timezone: "America/Toronto"
