---
# this controls our build in Satellite

satellite_fqdn: "satellite.{{ _global_domain_name }}"
satellite_admin_username: "{{ satellite_admin_username_vault }}"
satellite_admin_password: "{{ satellite_admin_password_vault }}"
satellite_initial_location: "Default Location"
satellite_initial_organization: "Default Organization"
satellite_location: "{{ satellite_initial_location }}"
satellite_organization: "{{ satellite_initial_organization }}"
satellite_domain: "{{ _global_domain_name }}"
satellite_server_url: "https://{{ satellite_fqdn }}"
satellite_validate_certs: true

search_dh_mac: "ff:ff:ff:ff:ff:ff"
# default_vm_mac: "00:50:56:ff:ff:ff"

post_deploy_timeout: 600  # seconds
use_sync_build: false
discovered_hosts_resource: "discovered_hosts"

# Base network info
_default_domain: "{{ _global_domain_name }}"
_default_subnetname: "{{ _global_domain_name }}"
_default_provision_iface: "eno1"
_default_vm_provision_iface: "ens192"

# Bond network
_default_bond_subnetname: "bond_subnet"
_default_bond_subnet_prefix: 23
_default_bond_default_gateway: 192.168.140.1
_default_bond_iface: "bond0"
_default_child_iface1: "enp2s0f0"
_default_child_iface2: "enp2s0f1"

# _default_bond_vlan_tag_meta: "940"


# Ansible 2.4 growth deployment
platform_hosts:
  - fqdn: "aapcontroller24.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel9_metal/aap_24"
    kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
    compute_resource: "baremetal"
    interfaces_attributes:
      - type: "interface"
        identifier: "{{ _default_provision_iface }}"
        domain: "{{ _default_domain }}"
        execution: true
        managed: true
        primary: true
        provision: true
        subnet: "{{ _default_subnetname }}"
        mac: "54:b2:03:f1:0b:d2"
        ip: "192.168.140.13"


  - fqdn: "aaphub24.{{ _global_domain_name }}"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel9_metal/aap_24"
    kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
    compute_resource: "baremetal"
    interfaces_attributes:
      - type: "interface"
        identifier: "{{ _default_provision_iface }}"
        domain: "{{ _default_domain }}"
        execution: true
        managed: true
        primary: true
        provision: true
        subnet: "{{ _default_subnetname }}"
        mac: "54:b2:03:f1:0b:6a"
        ip: "192.168.140.14"

# AAP 2.5 Growth Deployment
# platform_hosts:
#   - fqdn: "aapcontroller1.{{ _global_domain_name }}"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_metal/aap_25"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "baremetal"
#     interfaces_attributes:
#       - type: "interface"
#         identifier: "{{ _default_provision_iface }}"
#         domain: "{{ _default_domain }}"
#         execution: true
#         managed: true
#         primary: true
#         provision: true
#         subnet: "{{ _default_subnetname }}"
#         mac: "54:b2:03:f1:0b:d2"
#         ip: "192.168.140.13"
#   - fqdn: "aaphub1.{{ _global_domain_name }}"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_metal/aap_25"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "baremetal"
#     interfaces_attributes:
#       - type: "interface"
#         identifier: "{{ _default_provision_iface }}"
#         domain: "{{ _default_domain }}"
#         execution: true
#         managed: true
#         primary: true
#         provision: true
#         subnet: "{{ _default_subnetname }}"
#         mac: "54:b2:03:f1:0b:6a"
#         ip: "192.168.140.14"
#   - fqdn: "aapdb.{{ _global_domain_name }}"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_vm/dev/aap_25_vm"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "vcenter.{{ _global_domain_name }}"
#     mac: "00:50:56:ff:ff:ff"
#     ip: "192.168.140.15"
#   - fqdn: "aapgateway1.{{ _global_domain_name }}"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_vm/dev/aap_25_vm"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "vcenter.{{ _global_domain_name }}"
#     mac: "00:50:56:ff:ff:ff"
#     ip: "192.168.140.16"
#   - fqdn: "aapedacontroller.{{ _global_domain_name }}"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_vm/dev/aap_25_vm"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "vcenter.{{ _global_domain_name }}"
#     mac: "00:50:56:ff:ff:ff"
#     ip: "192.168.140.17"
