---

# piv_current_username: "idm_user"
# piv_current_user_csr_subject: "/CN=idm_user/DC=example/DC=ca/emailAddress=idm_user@{{ _global_domain_name }}"
# piv_current_realm: "{{ _global_domain_name }}"
